config/routes.rb
Rorshop::Application.routes.draw do
  resources :search_suggestions, :users, :shopping_carts
  post 'sessions/create', as: 'login'
  get 'sessions/destroy', as: 'logout'
  root 'products#welcome'
  get 'products/index'
  get 'products/:id/' => 'products#show', as: 'product'
  get 'products/filter'
  get '/shopping_carts/remove_item/:product_id', to: 'shopping_carts#remove_item', as: 'remove_item'
  get '/shopping_cart/order', to: 'shopping_carts#order', as: 'order'

  # Example resource route within a namespace:
  namespace :admin do
    # Directs /admin/products/* to Admin::ProductsController
    # (app/controllers/admin/products_controller.rb)
    resources :products, :types
    post 'type_values_controller/create'
  end

end

app/views/shared/_banner_header.html.haml
.banners-bg
  .main
    .clear
      .moduletable
        .bannergroup
          .banneritem
            %a{href: "#"}
              %img{alt: "Banner", src: "/assets/banner1.jpg"}/
            .clr
      .moduletable
        .slide-box
          .anythingSlider
            .wrapper{style: "overflow: hidden;"}
              %ul
                %li.slide1
                  %a.product-name{href: "#"}
                %li.slide2
                  %a.product-name{href: "#"}
                %li.slide3
                  %a.product-name{href: "#"}
            %a.arrow.forward >
            %a.arrow.back <
            #thumbNav
              %a{href: "#"} 1
              %a.cur{href: "#"} 2
              %a{href: "#"} 3
            %a#start-stop.playing{href: "#"} Stop

app/views/shared/_categories.html.haml
.module-categories
  = yield(:types)

app/views/shared/_footer.html.haml
#footer
  .space
    .footerText
      %ul.menu
        = render :partial => 'shared/menus'
      %div Copyright © 2014 Jewelry Online. All Rights Reserved.

app/views/shared/_login_box.html.haml
.module-login
  %h3
    %span Login Form
  .boxIndent
    = form_tag login_path, :class => 'form-login' do
      .part1
        .clear
          .username
            = text_field_tag :email, '', id: 'mod_login_username', placeholder: 'Email'
          .password
            = password_field_tag :password, '', id: 'mod_login_password', placeholder: '••••••'
        #inputs
          / <input type="submit" name="Submit" class="button" value="Log in">
          %input.button{name: "submit", type: "submit", value: "Logheaza-te"}/
      #form-login-remember
        %a{href: "#"}
          Ti-ai uitat parola
        %br/
        Nu ai cont inca?
        %br/
        %a.reg{href: "#"}
        = link_to 'Creaza-ti un cont', new_user_path

app/views/shared/_menu_header.html.haml
.menu-bg
  .main
    .clear
      #topmenu
        %ul.menu-nav
          = render :partial => 'shared/menus'
      #search
        .moduletable
          = form_tag products_index_path, :class => "pull-right navbar-search", :method => :get do
            = text_field_tag :search, params[:search], size: 30, 
              id: 'mod_search_searchword', placeholder: 'Cauta...'

app/views/shared/_menus.html.haml
%li#current.active.item53
  %a{href: "/"}
    %span Acasa
%li.item60
  %a{href: products_index_path}
    %span Magazin Online
%li.item56
  %a{href: "#"}
    %span Special
%li.item57
  %a{href: "#"}
    %span FAQ's
%li.item55
  %a{href: "#"}
    %span Stiri
%li.item58g
  %a{href: "#"}
    %span Contact

app/views/shared/_newsletter.html.haml
.module
  %h3
    %span Newsletter
  .boxIndent
    %form#subscribeFormModule{action: "#", method: "post", name: "subscribeFormModule"}
      .newslatter
        .width
          %span enter your e-mail
          %br/
          %input#email.moduleInput{maxlength: "250", name: "email", size: "10", type: "text", value: ""}/
          %input.button{name: "Submit", type: "submit", value: "Submit"}/
          %a{href: "#"} Unsubscribe

app/views/shared/_notices.html.haml
- flash.each do |type, message|
  .alert.fade.in{class: "#{bootstrap_class_for(type)}"}
    %button.close{"data-dismiss" => "alert"}
      ×
    = message.html_safe

app/views/shared/_products.html.haml
%table{border: "0", cellpadding: "0", cellspacing: "0", width: "100%"}
  %tbody
    - (0..2).each do |counter|
      %tr
        - limit_left = counter * 3;
        - limit_right = ((counter + 1) * 3 - 1);
        - if @results[limit_left]
          - @results[limit_left..limit_right].each do |product|
            = render :partial => 'shared/products/product_main_page', :locals => {:product => product}

app/views/shared/_slide_js.html.haml
:javascript
  //<![CDATA[
  try{if (!window.CloudFlare) {var CloudFlare=[{verbose:0,p:0,byc:0,owlid:"cf",bag2:1,mirage2:0,oracle:0,paths:{cloudflare:"/cdn-cgi/nexp/dok8v=02fcfa4f56/"},atok:"be07df6be1120748739b7ed202c6099f",petok:"1f777329688940a48c1183965f6d0abb82049942-1393604731-1800",zone:"template-help.com",rocket:"0",apps:{"abetterbrowser":{"ie":"7"},"ga_key":{"ua":"UA-7078796-5","ga_bs":"2"}}}];var a=document.createElement("script"),b=document.getElementsByTagName("script")[0];a.async=!0;a.src="//ajax.cloudflare.com/cdn-cgi/nexp/dok8v=221574e73d/cloudflare.min.js";b.parentNode.insertBefore(a,b);}}catch(e){};
  //]]>
:css
  .cf-hidden { display: none; } .cf-invisible { visibility: hidden; }
:javascript
  jQuery.noConflict();
  
  	function formatText(index, panel) {
  		return index + "";
  	}
  
  	jQuery(function () {
  
  		jQuery('.anythingSlider').anythingSlider({
                  easing: "easeInOutBack",		// Anything other than "linear" or "swing" requires the easing plugin
                  autoPlay: true,					// This turns off the entire FUNCTIONALY, not just if it starts running or not.
                  delay: 3000,					// How long between slide transitions in AutoPlay mode
                  startStopped: false,			// If autoPlay is on, this can force it to start stopped
                  animationTime: 1000,				// How long the slide transition takes
                  hashTags: true,					// Should links change the hashtag in the URL?
                  buildNavigation: true,			// If true, builds and list of anchor links to link to each slide
          		pauseOnHover: true,				// If true, and autoPlay is enabled, the show will pause on hover
          		startText: "Go",				// Start text
  		        stopText: "Stop",				// Stop text
  		        navigationFormatter: formatText		// Details at the top of the file on this use (advanced use)
  		      });
  
  		jQuery("#slide-jump").click(function(){
  			jQuery('.anythingSlider').anythingSlider(6);
  		});
  
  	});
:javascript
  /* <![CDATA[ */
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-7078796-5']);
  _gaq.push(['_trackPageview']);

  (function() {
  	var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
  	ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
  	var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

  (function(b){(function(a){"__CF"in b&&"DJS"in b.__CF?b.__CF.DJS.push(a):"addEventListener"in b?b.addEventListener("load",a,!1):b.attachEvent("onload",a)})(function(){"FB"in b&&"Event"in FB&&"subscribe"in FB.Event&&(FB.Event.subscribe("edge.create",function(a){_gaq.push(["_trackSocial","facebook","like",a])}),FB.Event.subscribe("edge.remove",function(a){_gaq.push(["_trackSocial","facebook","unlike",a])}),FB.Event.subscribe("message.send",function(a){_gaq.push(["_trackSocial","facebook","send",a])}));"twttr"in b&&"events"in twttr&&"bind"in twttr.events&&twttr.events.bind("tweet",function(a){if(a){var b;if(a.target&&a.target.nodeName=="IFRAME")a:{if(a=a.target.src){a=a.split("#")[0].match(/[^?=&]+=([^&]*)?/g);b=0;for(var c;c=a[b];++b)if(c.indexOf("url")===0){b=unescape(c.split("=")[1]);break a}}b=void 0}_gaq.push(["_trackSocial","twitter","tweet",b])}})})})(window);
  /* ]]> */

app/views/shared/_top_header.html.haml
- user = current_user
.main
  .clear.currency-bg
    #logo
      %a{href: "/"}
        %img{alt: "", src: "/assets/logo.jpg"}/
    .float-right
      .currency
        .moduletable
          - if is_logged_in
            %h3 
              Bine ai venit 
              = link_to user.name, user_path(user)
          - else
            %h3 Bine ai venit vizitatorule
      .cart
        .moduletable2
          - if @shopping_cart.total_unique_items != 0
            = @shopping_cart.total_unique_items
            produs(e) -
            = @shopping_cart.total
            RON
            %a{href: "#{shopping_cart_path(@shopping_cart)}"} Vizualizeaza
          - else
            Cosul dumneavoastra e gol